### ISSUE TITLE
just wondering why it feels so heavy.

### ISSUE THREAD

**Issue by Shad0wSeven** [ISODN/USNCO-web#47]
CODSSite seems to be a pretty static website, with just many pages of fairly static content, which makes me wonder why a loading modal is needed, as there shouldn't really be a need to spend around half a second to a second loading essentially a static website? Just wondering if there are any really interesting backend things going on that require the need of a long waiting period rather than fairly instant between switching pages - also looking at going from a category to a subpage, those seem fairly instant, why are animations needed?

**Comment by Jerdan1980** [comment]
The loading modal was a result of people being confused by text flashing as it loads in through the website. It was very apparent earlier on when the website was on the free tier. You can still see a little bit of flashing when going through subpages. It just keeps the user from seeing the content load in.
The backend stores all the pages on the cloud to allow people to login to the website and make changes there, instead of interacting with github. This will be changed (in version 2) to store all the pages as files on github moving forward to fix these issues and make the website lighter.

**Comment by Shad0wSeven** [comment]
ah ic thanks!
